# Generated by Django 4.2.6 on 2023-11-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_likes_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='post_like',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='user_like',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_post',
        ),
    ]
