# Generated by Django 4.2.6 on 2023-11-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tot_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
