# Generated by Django 4.2.6 on 2023-11-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='timestamp',
        ),
    ]
