# Generated by Django 4.2.7 on 2023-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_follower_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.TextField(blank=True, default='https://th.bing.com/th/id/OIP.U6GEahoDCyMwPQIHCGiSlAHaHa?rs=1&pid=ImgDetMain', max_length=800),
        ),
    ]
