# Generated by Django 4.2.6 on 2023-11-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user_followed', 'user_follower')},
        ),
    ]
